[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r backend/requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn --chdir backend wsgi:application"
